server:
  port: 9090
spring:
  application:
    name: yetusote
  data:
    mongodb:
      uri: mongodb+srv://yetusote:yetusote@cluster0.nycig.mongodb.net/yetusote?retryWrites=true&w=majority&appName=Cluster0
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      enabled: false

